services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: minecube
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "8888:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: